config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'opinions#index'

  resources :opinions do
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: :show do
    resources :favorites, only: [:new, :create, :update, :destroy]  do
      member do
        put :price_and_profit
      end
    end
  end

  post 'search_stock_data', to: 'opinions#search_stock_data', as: :search_stock_data
  
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  has_many  :comments

  with_options presence: true do
    validates :brand, format: { with: /\A[A-Z]{1,4}\z/, message: "is invalid.Please enter an alphabet of four letters or less"}
    validates :privacy_id, numericality: { other_than: 1 , message: "can't be blank"}
    validates :theory
  end
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :set_params, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, except: [:index, :new, :create, :show, :search_stock_data]

  def index
    @opinions = Opinion.where(privacy_id: 2).includes(:user).order('created_at DESC')

    @aapl_data = get_stock_data('AAPL')
    @msft_data = get_stock_data('MSFT')
    @amzn_data = get_stock_data('AMZN')
  end

  def new
    @opinion = Opinion.new
    @opinions = Opinion.where(brand: @symbol, privacy_id: 2).includes(:user).order('created_at DESC')
  end

  def create
    @opinion = Opinion.new(opinion_params)
    if @opinion.save
      redirect_to user_path(current_user)
    else
      @opinions = Opinion.where(brand: @symbol, privacy_id: 2).includes(:user).order('created_at DESC')
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @opinion.comments.includes(:user).order('created_at DESC')
  end

  def edit
  end

  def update
    if @opinion.update(opinion_params)
      redirect_to user_path(@opinion.user) 
    else
      render :edit
    end
  end

  def destroy
    if current_user == @opinion.user
      @opinion.comments.destroy_all
      @opinion.destroy
    else
      render  :index
    end
    redirect_to user_path(current_user)
  end

  def search_stock_data
    require 'httparty'
    symbol = params[:symbol]
    api_key = ENV["ALPHA_VANTAGE_API_KEY"]
    url = "https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=#{symbol}&apikey=#{api_key}"
    uri = URI(url)
    response = Net::HTTP.get(uri)
    data = JSON.parse(response)

    @symbol = params[:symbol]

    if data["Time Series (Daily)"]
      time_series = data["Time Series (Daily)"]
      latest_date = time_series.keys.first
      @stock_data = {
        latest_date: latest_date,
        latest_close_price: time_series[latest_date]["4. close"]
      }
      @symbol = symbol
      @opinions = Opinion.where(brand: @symbol, privacy_id: 2).includes(:user).order('created_at DESC')
    else
      @stock_data = nil
      @symbol = nil
      @opinions = []
    end
    @opinion = Opinion.new
    render :new
  end

  private

  def get_stock_data(symbol)
    api_key = ENV["ALPHA_VANTAGE_API_KEY"]
    interval = '1min'
  
    url = "https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=#{symbol}&interval=#{interval}&apikey=#{api_key}"
    response = HTTParty.get(url)
    data = JSON.parse(response.body)
  
    if data['Time Series (1min)']
      latest_data = data['Time Series (1min)'].first[1]
      latest_close_price = latest_data['4. close']
      latest_date = data['Time Series (1min)'].first[0]
  
      return {
        latest_close_price: latest_close_price,
        latest_date: Time.parse(latest_date).utc
      }
    else
      return {
        latest_close_price: 'Data not available',
        latest_date: 'Data not available'
      }
    end
  end

  def opinion_params
    params.require(:opinion).permit(:brand, :privacy_id, :theory).merge(user_id: current_user.id)
  end

  def set_params
    @opinion = Opinion.find_by(id: params[:id])
    unless @opinion
      redirect_to root_path
    end
  end

  def move_to_index
    return if current_user == @opinion.user

    redirect_to root_path
  end

end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/views/opinions/edit.html.erb
<%= render "shared/header" %>

<div class="form">
  <div class="edit_container">

    <%= form_with model: @opinion, local: true do |f| %>
      <h2 class='table'>編集フォーム</h2>
      <%= f.text_field :brand, class:"opinion_form_field", placeholder:"銘柄名" %>
      <%= f.collection_select(:privacy_id, Privacy.all, :id, :name, {}, {class:"opinion_form_field"}) %>
      <%= f.text_area :theory, class:"opinion_form_field", placeholder:"テキスト" %>
      <%= f.submit "投稿する" ,class:"btn" %></p>
    <% end %>

  </div>
</div>

app/views/opinions/index.html.erb
<%= render "shared/header" %>

<div class ="top">
  <div class="title-contents">
    <h2 class="servise-title">投資の体験アプリ</h2>
    <p>実際の米国銘柄に対してみんなで意見交換をしましょう！</p>
    <div class="search_btn">
    <%= link_to image_tag("search5.png", class:"search_icon"), new_opinion_path %>
    </div>
  </div>
</div>

<div class="stock_datas">
  <div class="stock_data">
    <%= image_tag "apple3.png", class:"brand_image" %>
    <p class="stock_barand">Apple</p>
    <p>現在値: <%= @aapl_data[:latest_close_price] %></p>
    <% if @aapl_data[:latest_date] != "Data not available" %>
      <p>取得日時: <%= @aapl_data[:latest_date].strftime("%Y-%m-%d %H:%M:%S") %></p>
    <% else %>
      <p>取得日時: no data</p>
    <% end %>
  </div>
  <div class="stock_data">
    <%= image_tag "microsoft.png", class:"brand_image" %>
    <p class="stock_barand">Microsoft</p>
    <p>現在値: <%= @msft_data[:latest_close_price] %></p>
    <% if @msft_data[:latest_date] != "Data not available" %>
      <p>取得日時: <%= @msft_data[:latest_date].strftime("%Y-%m-%d %H:%M:%S") %></p>
    <% else %>
      <p>取得日時: no data</p>
    <% end %>
  </div>
  <div class="stock_data">
    <%= image_tag "amazon.png", class:"brand_image" %>
    <p class="stock_barand">Amazon</p>
    <p>現在値: <%= @amzn_data[:latest_close_price] %></p>
    <% if @amzn_data[:latest_date] != "Data not available" %>
      <p>取得日時: <%= @amzn_data[:latest_date].strftime("%Y-%m-%d %H:%M:%S") %></p>
    <% else %>
      <p>取得日時: no data</p>
    <% end %>
  </div>
</div>

<div class='opinions_all'>
<h2 class='table'>最近の投稿</h2>
<% @opinions.each do |opinion| %>
  <p class='opinion_brand'><%= opinion.brand %></p>
  <p><%= opinion.theory %></p>
  <div class='opinion_detail'>
  <p class='contributor'>投稿者:<%=link_to opinion.user.name, user_path(opinion.user) %></p>
  <p>投稿時間:<%= opinion.created_at.strftime("%Y-%m-%d %H:%M:%S") %></p>
  </div>
<% end %>
</div>

<%= render "shared/footer" %>

app/views/opinions/new.html.erb
<%= render "shared/header" %>

<div class="search_content">
  <h2 class='table'>株価を検索しましょう！</h2>
  <%= form_tag search_stock_data_path, method: :post do %>
    <div class="search_form">
    <%= text_field_tag :symbol, nil, placeholder: 'AAPL,MSFT,AMZN' %>
    <%= submit_tag '検索' %>
    </div>
  <% end %>

  <% if @stock_data %>
   <h2><%= @symbol %>の終値</h2>
   <p>Date: <%= @stock_data[:latest_date] %></p>
   <p>Close Price: <%= @stock_data[:latest_close_price] %></p>
  <% else %>
   <p>No stock data available for the entered symbol.</p>
  <% end %>
</div>

<div class="opinion_form">
    <%= form_with model: @opinion, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
      <h2 class='table'>投稿フォーム</h2>
      <%= f.text_field :brand, class:"opinion_form_field", placeholder:"銘柄(ex.AAPL)" %>
      <%= f.collection_select(:privacy_id, Privacy.all, :id, :name, {}, {class:"opinion_form_field"}) %>
      <%= f.text_area :theory, class:"opinion_form_field", placeholder:"テキスト" %>
      <%= f.submit "投稿する" ,class:"btn" %></p>
    <% end %>
</div>
  
<div class='opinions_all'>
  <h2 class='table'>関連の投稿</h2>
    <% @opinions.each do |opinion| %>
      <p class='opinion_brand'><%= opinion.brand %></p>
      <p><%= opinion.theory %></p>
      <div class='opinion_detail'>
        <p class='contributor'>投稿者:<%=link_to opinion.user.name, user_path(opinion.user) %></p>
        <p>投稿時間:<%= opinion.created_at.strftime("%Y-%m-%d %H:%M:%S") %></p>
      </div>
    <% end %>
</div>

<%= render "shared/footer" %>

app/views/opinions/show.html.erb
<%= render "shared/header" %>

<div class='the_opinion'>
  <p class="opinion_brand"><%= @opinion.brand %></p>
  <p><%= @opinion.theory %></p>
  <p class='contributor'>投稿者:<%=link_to @opinion.user.name, user_path(@opinion.user) %></p>
  <p>投稿時間:<%= @opinion.created_at.strftime("%Y-%m-%d %H:%M:%S") %></p>
  <% if current_user == @opinion.user %>
    <%= link_to '編集する', edit_opinion_path(@opinion) %>
    <%= link_to '削除する', opinion_path(@opinion), method: :delete %>
  <% end %>  
</div>
 
<% if user_signed_in? %>
<div class="comment_bar">
  <%= form_with model: [@opinion, @comment], local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <div class="comment_form">
    <%= f.text_area :content, placeholder:"コメント" ,class: "comment_content" %>
    <%= f.submit "送信する", class: :form__btn  %>
    </div>
  <% end %>
</div>
<% end %>

<div class='comments'>
<h2 class='table'>投稿へのコメント</h2>
<% @comments.each do |comment| %>
  <p class="comment_main"><%= comment.content %></p>
  <div class='opinion_detail'>
    <% if current_user == comment.user %>
      <p class="comment_destroy"><%= link_to '削除する', [comment.opinion, comment], method: :delete %></p>
    <% end %>
      <p class='contributor'>投稿者:<%=link_to comment.user.name, user_path(comment.user) %></p>
      <p>投稿時間:<%= comment.created_at.strftime("%Y-%m-%d %H:%M:%S") %></p>
  </div>
<% end %>
</div>

<%= render "shared/footer" %>